# Manage this via sealed secrets
apiVersion: v1
kind: Secret
metadata:
  name: pg-superuser-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-user-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: app123