apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-additional-datasources
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    datasources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.monitoring.svc.cluster.local:3100
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: "-1h"
          spanEndTimeShift: "1h"
          tags:
            - key: "service.name"
              value: "service_name"
            - key: "host.name"
              value: "host"
          filterByTraceID: true
          filterBySpanID: false
          customQuery: true
          query: '{$${__tags}} |= "$${__trace.traceId}"'
        serviceMap:
          datasourceUid: prometheus
        nodeGraph:
          enabled: true
        search:
          hide: false
        lokiSearch:
          datasourceUid: loki

    - name: Loki
      type: loki
      uid: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 1000
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"traceId"\s*:\s*"([^"]+)"'
            name: TraceID
            url: "$${__value.raw}"