apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-additional-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      uid: "tempo"
      url: http://tempo.monitoring.svc.cluster.local:3100
      jsonData:
        httpMethod: GET
        lokiSearch:
          datasourceUid: "loki"
        serviceMap:
          datasourceUid: 'prometheus'

    - name: Loki
      type: loki
      uid: "loki"
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        derivedFields:
          - name: "TraceID"
            datasourceUid: "tempo"
            matcherRegex: "\"traceId\"\\s*:\\s*\"(\\w+)\""
            internalLinkEnabled: true
            internalLinkTargetUid: "tempo"