apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/open-telemetry/opentelemetry-operator.git
    targetRevision: main
    path: ""
    directory:
      recurse: false
  source:
    repoURL: https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/
    targetRevision: HEAD
    chart: ""
  source:
    repoURL: 'https://github.com/open-telemetry/opentelemetry-operator'
    targetRevision: v0.115.0
    path: 'bundle/'
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true