apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  config:
    connectors:
      servicegraph:
        dimensions:
          - k8s.namespace.name
          - k8s.pod.name

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25

    exporters:
      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317 
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/otlp
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp, servicegraph]

      metrics:
          receivers: [servicegraph]
          processors: [batch]
          exporters: [otlphttp/prometheus]