apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nestjs-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector-collector.monitoring.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_always_on
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest